module.exports = {
    "left":{
        "title":"学习链接",
        "study":[
            {
                "href":"http://www.bootcss.com/",
                "name":"BootStrap中文网"
            },
            {
                "href":"http://www.runoob.com/",
                "name":"菜鸟教程"
            },
            {
                "href":"http://api.jquery.com/",
                "name":"jQuery API"
            }
        ],
        "contact":[
            {"way":"微信号：WWW24362068"},
            {"way":"微信公众号：林斌的公众开发"},
            {"way":"QQ:826887204"}
        ]
    },
    "right":{
        "title":"赞助本站",
        "images":[
            {
                "src":"images/wx.png",
                "name":"微信二维码"
            },
            {
                "src":"images/ant.jpg",
                "name":"支付宝二维码"
            }
        ]
    }
}